---

parameters:
  output_dir: ./output
  use_subdir: true # This will pull all this run's images into a subdirectory in the output directory
  file_basename: image
  file_ext: png
  # image_dimensions: [1920, 1080] # 1080p
  # image_dimensions: [3840, 2160] # 4K
  image_dimensions: [300, 300] # 8K
  tile_dimensions: [1, 1] # Due to fun rayon/Rust quirks, a tile size of 1x1 is almost always the most efficient and fast.

  gamma_correction: 2.0
  samples_per_round: 10 # This is the number of samples per pixel. The higher the number, the less noisy the image is.
  round_limit: null # This is the number of rounds. A new image is generated after each round, and the previous rounds are averages into all the following rounds.
  max_bounces: 50 # This is the maximum number of bounces. After this many, the ray is terminated with color [0, 0, 0] (Black).
  use_scaling_truncation: true

  pixels_per_progress_update: 100 # I'd like to be able to remove this parameter, but I haven't worked out the maths yet.
  progress_memory: 50 # This determines how "reactive" the progress tracker is. A lower number means more reactive.

scene: !inline 
  name: cornell_box
  geometrics:
    - left_wall
    - right_wall
    - floor
    - ceiling
    - back_wall
    - front_wall

    # - ceiling_light
    # - ceiling_light_dim

    - far_left_box
    - near_right_box
    - near_right_box_internal
    # - center_box_rotated
  use_bvh: true
  camera: basic
  background_color: [0.0, 0.0, 0.0]

cameras:
  basic:
    vertical_field_of_view_degrees: 40
    eye_location: [0.5, 0.5, 1.44144]
    target_location: [0.5, 0.5, 0]
    view_up: [0, 1, 0]
    defocus_angle_degrees: 0
    focus_distance: !eye_to_target

geometrics:
  left_wall: !parallelogram
    lower_left: [0, 0, 0]
    u: [0, 0, -1]
    v: [0, 1, 0]
    material: lambertian_cb_green
  right_wall: !parallelogram
    lower_left: [1, 0, -1]
    u: [0, 0, 1]
    v: [0, 1, 0]
    material: lambertian_cb_red
  floor: !parallelogram
    lower_left: [0, 0, 0]
    u: [1, 0, 0]
    v: [0, 0, -1]
    # material: lambertian_cb_white
    material: lambertian_mike_face
  ceiling: !parallelogram
    lower_left: [0, 1, -1]
    u: [1, 0, 0]
    v: [0, 0, 1]
    # material: lambertian_cb_white
    material: lambertian_mike_face_glow
  back_wall: !parallelogram
    lower_left: [0, 0, -1]
    u: [1, 0, 0]
    v: [0, 1, 0]
    # material: lambertian_cb_white
    material: lambertian_mike_face
  front_wall: !parallelogram
    lower_left: [1, 0, 0]
    u: [-1, 0, 0]
    v: [0, 1, 0]
    is_culled: true
    material: lambertian_cb_white

  ceiling_light: !parallelogram
    lower_left: [0.35, 0.999, -0.65]
    u: [0.3, 0, 0]
    v: [0, 0, 0.3]
    material: lambertian_white_light
  ceiling_light_dim: !parallelogram
    lower_left: [0.35, 0.999, -0.65]
    u: [0.3, 0, 0]
    v: [0, 0, 0.3]
    material: lambertian_white_light_dim

  far_left_box_core: !box
    a: [0.2, 0, -0.5]
    b: [0.5, 0.6, -0.8]
    # material: lambertian_cb_white
    material: dielectric_glass
  near_right_box_core: !box
    a: [0.5, 0, -0.2]
    b: [0.8, 0.3, -0.5]
    # material: lambertian_cb_white
    material: dielectric_glass
    # material: lambertian_mike_face_glow
  near_right_box_core_internal: !box
    a: [0.52, 0.02, -0.22]
    b: [0.78, 0.28, -0.48]
    # material: lambertian_cb_white
    # material: dielectric_glass
    material: lambertian_mike_face_glow
  
  far_left_box: !rotate_y
    # type: rotate_y
    geometric: # !inline
      type: inline
      # a: [0.2, 0, -0.5]
      # b: [0.5, 0.6, -0.8]
      # # material: lambertian_cb_white
      # material: dielectric_glass
    # angle: !degrees 15
    # around: [0.35, 0, -0.65]
  near_right_box: !rotate_y
    geometric: !ref near_right_box_core
    angle: !degrees -18
    around: [0.65, 0, -0.35]
  near_right_box_internal: !rotate_y
    geometric: !ref near_right_box_core_internal
    angle: !degrees -18
    around: [0.65, 0, -0.35]

materials:
  # lights
  lambertian_white_light: !lambertian
    reflectance_texture: solid_black
    emittance_texture: solid_white_light
  lambertian_white_light_dim: !lambertian
    reflectance_texture: solid_black
    emittance_texture: solid_white_light_dim
  lambertian_cb_red_light_dim: !lambertian
    reflectance_texture: solid_cb_red
    emittance_texture: solid_cb_red_light_dim
  lambertian_cb_green_light_dim: !lambertian
    reflectance_texture: solid_cb_green
    emittance_texture: solid_cb_green_light_dim

  # lambertians
  lambertian_cb_white: !lambertian
    reflectance_texture: solid_cb_white
    emittance_texture: solid_black
  lambertian_cb_red: !lambertian
    reflectance_texture: solid_cb_red
    emittance_texture: solid_black
  lambertian_cb_green: !lambertian
    reflectance_texture: solid_cb_green
    emittance_texture: solid_black

  # lambertian images
  lambertian_mike_face: !lambertian
    reflectance_texture: image_mike_face
    emittance_texture: solid_black
  lambertian_mike_face_glow: !lambertian
    reflectance_texture: image_mike_face
    emittance_texture: image_mike_face

  # dielectrics
  dielectric_glass: !dielectric
    reflectance_texture: solid_white
    emittance_texture: solid_black
    index_of_refraction: 1.5

  # speculars
  specular_mirror: !specular
    reflectance_texture: solid_white
    emittance_texture: solid_black
    roughness: 0

textures:
  # pures
  solid_white: !solid_color [1, 1, 1]
  solid_black: !solid_color [0, 0, 0]

  # lights
  solid_white_light: !solid_color [7, 7, 7]
  solid_white_light_dim: !solid_color [3, 3, 3]
  solid_cb_red_light_dim: !solid_color [0.325, 0.025, 0.025]
  solid_cb_green_light_dim: !solid_color [0.06, 0.225, 0.075]

  # lambertians
  solid_cb_white: !solid_color [0.73, 0.73, 0.73]
  solid_cb_red: !solid_color [0.65, 0.05, 0.05]
  solid_cb_green: !solid_color [0.12, 0.45, 0.15]

  # images
  image_mike_face: !image
    filename: texture_images/mike_face.png
    gamma: 2.0